
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-nfs-pv
  labels:
    pv: mongo-nfs-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /home/centos/nfs/data/mongo
    server: 10.0.0.52
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongo-nfs-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  selector:
    matchLabels:
      pv: mongo-nfs-pv
